import styles from "./styles.module.css";

const UserCard = () => {
  // const history = useHistory();

  // const loginHandler = () => {
  //   history.replace("/app");
  // };

  return (
    <div className={styles.wrapper}>
      <div claclassNamess={styles.left}>
        <img src="https://i.imgur.com/bxgzvrp.jpg" alt="user" width="500"></img>
        {/* <img src="./logo192.jpg" alt="user" width="400" /> */}
        <div className={styles.underImageText}>
          <h4>Alex William</h4>
          <p>Astronaut</p>
        </div>
      </div>
      <div className={styles.right}>
        <div className={styles.info}>
          <h3>Information</h3>
          <div className={styles.info_data}>
            <div className={styles.data}>
              <h4>Email</h4>
              <p>alex@gmail.com</p>
            </div>
            <div className={styles.data}>
              <h4>Phone</h4>
              <p>0001-213-998761</p>
            </div>
          </div>
        </div>

        <div className={styles.projects}>
          <h3>Expeditions</h3>
          <div className={styles.projects_data}>
            <div className={styles.data}>
              <h4>Expedition 1</h4>
              <p>
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
              </p>
            </div>
            <div className={styles.data}>
              <h4>Expedition 2</h4>
              <p>
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
              </p>
            </div>
          </div>
          <div>
            <h3>About</h3>
            <div className={styles.data}>
              <p>
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
                ....................................
              </p>
            </div>            
          </div>
        </div>
      </div>
    </div>
  );
};

export default UserCard;
